name: Maven Basic Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 18.0.2
          distribution: 'liberica'
          java-package: jdk+fx
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml